[package]

name = "utp"
version = "0.1.0"
authors = ["Ricardo Martins <ricardo@scarybox.net>"]

[dependencies.time]
git = "https://github.com/rust-lang/time"

[lib]
name = "utp"

[[bin]]
name = "utp-cat"
path = "examples/utp-cat/main.rs"
test = false
